remote_theme: rundocs/jekyll-rtd-theme

title: PyArr
description: PyArr is a Python Sonarr and Radarr API Wrapper

plugins:
  - jekyll-default-layout
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
