---

name: PyArr CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  black:
    name: Check PyArr formatting with Balck
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running Black Check
        uses: lgeiger/black-action@master
        with:
          args: ". --check"
  build-n-publish:
    name: Build and publish PyArr 🐍 distribution 📦 to PyPI
    needs: [black]
    runs-on: ubuntu-18.04
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pep517
          run: >-
            python -m
            pip install
            pep517
            --user
        - name: Build a binary wheel and a source tarball
          run: >-
            python -m
            pep517.build
            --source
            --binary
            --out-dir dist/
            .
        - name: Publish distribution 📦 to PyPI
          if: startsWith(github.event.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.pypi_password }}
